version: '3'

services:
  shortner:
    image: ecommerce
    container_name: ecommerce
    hostname : ecommerce
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: >
      bash -c "
      /usr/bin/supervisord
      && /usr/bin/supervisorctl stop all
      && /usr/bin/supervisorctl start ecommerce
      && sleep infinity"
    volumes:
      - /var/log/UrlShortner:/var/log/ecommerce:rw
    ports:
      - "5000:5000"
